qcacmn: Move IPA_TCL_DATA_RING_IDX under IPA_OFFLOAD guarding
Subsequent to 744bb44 ("qcacmn: discard IPA TX ring flush before RTPM suspend")

This corrects the following compilation error:

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/dp/wifi3.0/dp_main.c: In function 'dp_runtime_suspend':
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/dp/wifi3.0/dp_main.c:10576:34: error: 'IPA_TCL_DATA_RING_IDX' undeclared (first use in this function); did you mean 'MAX_TCL_DATA_RINGS'?
10576 |                         if (i == IPA_TCL_DATA_RING_IDX)
      |                                  ^~~~~~~~~~~~~~~~~~~~~
      |                                  MAX_TCL_DATA_RINGS

This reverts commit 20ecde9 ("qcacmn: Declare IPA_TCL_DATA_RING_IDX unconditionally")

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>